### PR TITLE
Remove declaration of updateCamera

### LINKED ISSUE #4919: [compile error] Viewer->updateCamera() PCL1.11.1 vs PCL1.12.0
Hi,
I would like to ask you for a help. I started to use PCL 1.12.0 everything works fine for me. Except command `viewer->updateCamera()`. When I used  PCL version 1.11.1 and mentioned command worked fine without errors for me. Did anything changed with this command? Should I add/link same new Additional Dependency?

Here is code example which worked with PCL1.11.1 but with PCL1.12.0 doesn't :

```cpp
#include <pcl/io/pcd_io.h>
#include <boost/thread/thread.hpp>
#include <pcl/visualization/pcl_visualizer.h>

int main(int argc, char** argv)
 {	
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	
	if (pcl::io::loadPCDFile<pcl::PointXYZ>("file.pcd", *cloud) != 0)
	{
		return -1;
	}

	boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer("Viewer"));
	viewer->addPointCloud<pcl::PointXYZ>(cloud, "cloud");	
	viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "cloud");
	viewer->updateCamera();

	while (!viewer->wasStopped())
	{
		viewer->spinOnce(100);
		boost::this_thread::sleep(boost::posix_time::microseconds(100000));
	}

	return 0;
 } 
```
 Here is Error:

```
1>PCL_test.obj : error LNK2001: unresolved external symbol "public: void __cdecl pcl::visualization::PCLVisualizer::updateCamera(void)" (?updateCamera@PCLVisualizer@visualization@pcl@@QEAAXXZ)
1>C:\Users\trebu\source\repos\PCL_test\x64\Release\PCL_test.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "PCL_test.vcxproj" -- FAILED.
```

OS: Windows 10
Environment: Visual Studio 2019
Installer: PCL-1.12.0-AllInOne-msvc2019-win64.exe

### PR DESCRIPTION
**Pull request by larshg**
Fixes #4919

### CODE REVIEW

**Comment by mvieth** [comment]
A runtime warning is IMO not as good as a compile time deprecation warning. And in [this commit](https://github.com/PointCloudLibrary/pcl/commit/f45fa48b2e7e6cdc1cf9e77db832250cc70f9d84#diff-2536e9b457deae42dd9ca8fb9d137ac740d7501a524ba8e7fbd197666fed2150) it was replaced with the malfunctioning deprecation warning, so there are certain versions where neither works (1.11.0, 1.11.1, and 1.12.0 it seems). So the safest way would be to deprecate it properly now

**Comment by larshg** [comment]
I have updated it to properly deprecate it.

**Review by mvieth — APPROVED** [review]

**Review by kunaltyagi — APPROVED** [review]
