### PR TITLE
Fix gpu module building with cuda 13.2

### LINKED ISSUE #6423: [gpu] CUDA 13.2 build fails
**Describe the bug**

When upgrading from cuda 13.1 to 13.2, building PCL fails with the following error:
```
pcl/gpu/utils/include/pcl/gpu/utils/device/functional.hpp(89): error: namespace "cuda::std" has no member "identity"
    using cuda::std::identity
```

**Context**
- OS: Ubuntu 24.04
- PCL version: latest master branch
- CUDA version: 13.2

**Expected behavior**

Successful build.

**Current Behavior**

Above error.

**To Reproduce**

Build PCL with CUDA and the GPU module on CUDA 13.2. 

**Possible Solution**

Handle another CUDA version check where `std::identity` is used for newer versions.

### PR DESCRIPTION
**Pull request by jmackay2**
Cuda 13.2 ships the identity type but it lives in the libcu++ header. We should include `<cuda/std/functional>` to ensure `cuda::std::identity` is defined. This fixes the build for CUDA 13.2.

This was tested on Ubuntu 24.04 with CUDA 13.2 and CUDA 12.9. 

Fixes https://github.com/PointCloudLibrary/pcl/issues/6423

### CODE REVIEW

**Review by mvieth — APPROVED** [review]
Thanks!
