### ISSUE TITLE
Compilation error related to symmetric ICP objective

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3462]
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7.4
* PCL Version: master

Got the following error compiling a downstream project with the fresh master:

```cpp
/usr/local/include/pcl-1.9/pcl/registration/icp.h:347:13: error: no matching function for call to ‘boost::shared_ptr<pcl::registration::TransformationEstimation<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal, double> >::reset(boost::shared_ptr<pcl::registration::TransformationEstimationSymmetricPointToPlaneLLS<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal, double> >&)’
             transformation_estimation_.reset (symmetric_transformation_estimation);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is clearly caused by #3390. The problem and the fix are obvious, but what needs to be checked is how this escaped surfacing during unit tests.

**Comment by taketwo** [comment]
> what needs to be checked is how this escaped surfacing during unit tests

Turns out we do not have any unit tests for `IterativeClosestPointWithNormals`.
