### ISSUE TITLE
Fails to build with boost 1.70

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#2932]
```
[...]
In file included from .../work/pcl-pcl-1.9.1/segmentation/src/supervoxel_clustering.cpp:49:
In file included from .../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:43:
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: error: 'checked_delete<const pcl::SupervoxelClustering<pcl::PointXYZRGB>::SupervoxelHelper>' is missing exception specification 'noexcept'
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
                                                                                                                 noexcept
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:722:75: note: in instantiation of template class 'pcl::SupervoxelClustering<pcl::PointXYZRGB>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGB,pcl::SupervoxelClustering<pcl::PointXYZRGB>::VoxelData>::addPoint (const pcl::PointXYZRGB &new_point);
                                                                          ^
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: error: 'checked_delete<const pcl::SupervoxelClustering<pcl::PointXYZRGBA>::SupervoxelHelper>' is missing exception specification 'noexcept'
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
                                                                                                                 noexcept
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:726:76: note: in instantiation of template class 'pcl::SupervoxelClustering<pcl::PointXYZRGBA>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGBA,pcl::SupervoxelClustering<pcl::PointXYZRGBA>::VoxelData>::addPoint (const pcl::PointXYZRGBA &new_point);
                                                                           ^
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: error: 'checked_delete<const pcl::SupervoxelClustering<pcl::PointXYZ>::SupervoxelHelper>' is missing exception specification 'noexcept'
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
                                                                                                                 noexcept
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:738:72: note: in instantiation of template class 'pcl::SupervoxelClustering<pcl::PointXYZ>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZ,pcl::SupervoxelClustering<pcl::PointXYZ>::VoxelData>::addPoint (const pcl::PointXYZ &new_point);
                                                                       ^
.../work/pcl-pcl-1.9.1/segmentation/include/pcl/segmentation/supervoxel_clustering.h:528:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
3 errors generated.
```

Original FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236595

**Comment by SergioRAgostinho** [comment]
Closing it as a duplicate of #2931.
