### PR TITLE
Fix error: misplaced deprecation attributes in `vtkVertexBufferObject{,Mapper}`

### PR DESCRIPTION
**Pull request by SunBlack**
Fixes an issue introduced in #4065. Didn't saw it earlier as gcc8 doesn't complain and my Clang 10 build is still broken.
```
/home/sunblack/dev/pcl/visualization/include/pcl/visualization/vtk/vtkVertexBufferObjectMapper.h:39:6: error: misplaced attributes; expected attributes here
class PCL_EXPORTS vtkVertexBufferObjectMapper : public vtkMapper
     ^
     PCL_DEPRECATED(1, 13, "The OpenGL backend of VTK is deprecated. Please switch to the OpenGL2 backend.")

```

Note: Running clang-format will be fun for this:
```
class PCL_DEPRECATED(
    1,
    13,
    "The OpenGL backend of VTK is deprecated. Please switch to the OpenGL2 backend.")
    PCL_EXPORTS vtkVertexBufferObject : public vtkObject {
```

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
This highlights one of the stages we forgot in the release cycle. A release candidate :)

**Comment by SunBlack** [comment]
Interesting thing: MSVC complains it like Clang 10. Sad GCC doesn't :-(
