### PR TITLE
Fix missing closing parenthesis in cutil_inline_runtime.h

### PR DESCRIPTION
**Pull request by SunBlack**
Issue introduced in #3804:
```
[ 44%] Linking CXX shared library ../../lib/libpcl_gpu_features.so
/home/sunblack/dev/pcl/cuda/common/include/pcl/cuda/cutil_inline_runtime.h(130): error: expected a ")"
```

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Merged it fast because it was a simple hotfix
