### ISSUE TITLE
tests fail to compile with xcode 5.1

### ISSUE THREAD

**Issue by gcasey** [PointCloudLibrary/pcl#717]
With the most recent xcode the tests using gtest fail to compile on include of gtest-port.h

/Users/caseygoodlett/Projects/pcl/pcl/test/gtest-1.6.0/include/gtest/internal/gtest-port.h:499:13: fatal error: 
      'tr1/tuple' file not found

I believe this has been fixed in newer gtest version.
