### PR TITLE
Enable Real Sense 2 grabber for all platforms

### PR DESCRIPTION
**Pull request by SunBlack**
I setup a new VM and wondered why neither Clang or GCC needed to build anything after adding lbrealsense dependency like in the docker image. As I [don't see any reason](https://github.com/IntelRealSense/librealsense/tree/v2.0.0#compatible-platforms) why it is limited to Windows I removed the check for `Win32` (interesting that no one noticed it during creating the Dockerfile).

Remove limitation of librealsense 2.x to Windows only, including several fixes:
* Fix warning: function previously declared with an explicit exception specification redeclared with an implicit exception specification [-Wimplicit-exception-spec-mismatch] RealSense2Grabber::~RealSense2Grabber ()
* Fix warning: comparison of integers of different signs: 'int' and 'std::size_t'
* Fix error: use of undeclared identifier 'size' (issue introduced in #4190)
* Fix error: variable 'cloud_texture_ptr' must have explicitly specified data sharing attributes

### CODE REVIEW

File: io/src/real_sense_2_grabber.cpp [hunk 1]
```diff
@@ -286,14 +286,15 @@ namespace pcl
     cloud->width = sp.width ();
     cloud->height = sp.height ();
     cloud->is_dense = false;
-    cloud->points.resize ( size () );
+    cloud->points.resize ( points.size () );
```
Comment (larshg) [inline io/src/real_sense_2_grabber.cpp:289]:
```suggestion
    cloud->resize ( points.size () );
```

**Review by kunaltyagi — APPROVED** [review]

**Comment by SunBlack** [comment]
@kunaltyagi: The new title sounds like we support now all platforms except Windows (if you don't know the state before), but this is wrong, as Windows was already supported ;-)

**Review by larshg — APPROVED** [review]
