### ISSUE TITLE
pcl_visualization build failure on Mac OS X

### ISSUE THREAD

**Issue by asmaloney** [PointCloudLibrary/pcl#712]
I was excited to see that #363 was finally merged, so I updated all the support libs and of pcl using git to try to compile on Mac OS X 10.8.

I configured pcl like this:

``` sh
    cmake -DCMAKE_BUILD_TYPE:STRING=Release \
        -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING="10.8" \
        -DCMAKE_OSX_SYSROOT:PATH="<path to 10.8 SDK>" \
        -DQT_QMAKE_EXECUTABLE:FILEPATH="<path to Qt 5>" \
        -DQVTK_LIBRARY:FILEPATH="<path>/libvtkGUISupportQt-6.2.dylib" \
        -DBoost_INCLUDE_DIR:PATH="<path>" \
        -DEIGEN_INCLUDE_DIR:PATH="<path>" \
        -DBUILD_OPENNI:BOOL=OFF \
        pcl
```

I am using the VTK git master branch which I configured using this:

``` sh
    cmake -DCMAKE_BUILD_TYPE:STRING=Release \
        -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING="10.8" \
        -DCMAKE_OSX_SYSROOT:PATH="<path to 10.8 SDK>" \
        -DBUILD_TESTING:BOOL=OFF \
        -DVTK_QT_VERSION:STRING=5 \
        -DQT_QMAKE_EXECUTABLE:FILEPATH="<path to Qt 5>" \
        -DCMAKE_PREFIX_PATH:PATH="<path to Qt 5>"/lib/cmake \
        -DModule_vtkGUISupportQt:BOOL=ON \
        -DModule_vtkGUISupportQtOpenGL:BOOL=ON \
        -DModule_vtkRenderingQt:BOOL=ON \
        -DModule_vtkViewsQt:BOOL=ON \
     vtk
```

When compiling, I get the following errors:

```
[ 37%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm.o
PCL/pcl/visualization/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm:188:77: error: 
      no member named 'GetCocoaServer' in 'vtkCocoaRenderWindowInteractorFix'
    vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                      ~~~~  ^
/PCL/pcl/visualization/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm:189:16: error: 
      no member named 'GetCocoaServer' in 'vtkCocoaRenderWindowInteractorFix'
    if (!this->GetCocoaServer ())
         ~~~~  ^
/PCL/pcl/visualization/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm:192:13: error: 
      no member named 'SetCocoaServer' in 'vtkCocoaRenderWindowInteractorFix'
      this->SetCocoaServer (reinterpret_cast<void*> (server));
      ~~~~  ^
/PCL/pcl/visualization/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm:206:77: error: 
      no member named 'GetCocoaServer' in 'vtkCocoaRenderWindowInteractorFix'
    vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
```

Is this something that needs to be fixed for the new VTK integration or is it something I need to change in my configuration?

Thank you for your help.
