### PR TITLE
Fix compilation issues with CUDA 9.1

### LINKED ISSUE #2207: PCL build fails with CUDA 9.1 on Ubuntu
This is a followup to issue #2181, which fixed some, but not all CUDA 9.1 compilation issues.

PCL fails to build with CUDA 9.1 on Ubuntu with the following error...

`/usr/local/cuda/include/thrust/system/cuda/detail/transform.h(118): error: no instance of function template "pcl::cuda::NormalDeviationKernel<Storage>::operator() [with Storage=pcl::cuda::Device]" matches the argument list
            argument types are: (thrust::detail::tuple_of_iterator_references<const pcl::cuda::PointXYZRGB &, float4 &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>)
            object type is: pcl::cuda::NormalDeviationKernel<pcl::cuda::Device>`

The offending line is #88 in normal_3d.cu

`thrust::transform (thrust::make_zip_iterator (thrust::make_tuple (begin, output)), thrust::make_zip_iterator (thrust::make_tuple (begin, output)) + (end-begin), output, nd);`

I tried to fix with "thrust::raw_reference_cast" as mentioned in issue #2181, but not luck.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Superseeds and closes #2208, fixes #2207.

This allows compilation for me in CUDA 9.1 and CUDA 8.0.

@taketwo @cmcmurrough @Robzz please give it a try.

~**Edit:** Not ready yet. Found more errors of the same type.~

### CODE REVIEW

**Comment by Robzz** [comment]
Just saw your edit, I'll wait until you think this is ready, but FYI #2207 works for me (Windows) and for colleagues running both Linux and OS X. We had some other breakage but that's related to another recent merge, nothing to do with CUDA.

**Comment by SergioRAgostinho** [comment]
I haven't built all the stuff in the GPU module but the fix is similar for all. The operator needs to be defined with a const argument.

I also added some modifications to suppress the deprecations messages that started popping up.

**Comment by jasjuang** [comment]
I can also confirm this PR fixes the compilation problem with CUDA 9.1 on Ubuntu 16.04 for me. Look forward to see this getting merged!

**Comment by taketwo** [comment]
Same here, compiles fine 16.04 + 9.1.

**Comment by Robzz** [comment]
This doesn't break anything for me on Windows but I wasn't able to get anyone on Linux or OS X to build it so far.

**Comment by SergioRAgostinho** [comment]
I'm not sure we're gonna get many OSX users on this. Macbooks stopped shipping Nvidias a while back. 

I did hear recently that some support was added for running external cards but there's been no report whatsoever from our users in this configuration.

Just out of completeness @fran6co you wouldn't happen to be running an OSX with an Nvidia card to give it a try to this thing would you?

I'll ask around the mailing list as well.

**Comment by fran6co** [comment]
@SergioRAgostinho sorry, I don't have a Nvidia card to give it a test.

**Comment by Robzz** [comment]
I have a coworker working on a Mac with a nVidia card, I'll ask her to try it out if she has the time.

**Comment by paulsoning** [comment]
MacOS 10.13.4 Beta with CUDA 9.1 build was okay

**Comment by cmcmurrough** [comment]
I tested on Ubuntu 16.04 LTS x64 with CUDA 9.1. It works.

**Comment by SergioRAgostinho** [comment]
@PointCloudLibrary/maintainers need a merge on this please.
