### ISSUE TITLE
Correspondence grouping error - VTK

### ISSUE THREAD

**Issue by jcgarciaca** [PointCloudLibrary/pcl#1721]
Hello,
I upgraded to `pcl-1.8` and `vtk-7.1` but when I try to run the correspondence grouping tutorial here: [http://pointclouds.org/documentation/tutorials/correspondence_grouping.php#correspondence-grouping](url), I got a couple of errors with `catkin_make`. So I added some `#include` instructions to solve them, but when running the program `milk.pcd` and `milk_cartoon_all_small_clorox.pcd` I get:

`Correspondences found: 13`
`Model instances found: 0`

Although it worked previously. Is it normal? I tried to change the algorithm params but the result was the same. Is it just to "play" with the params until I get it working or could be something deeper?

Additionally, I get some errors

`Generic Warning: In /home/juliocesar/projects/VTK/Rendering/Core/vtkPolyDataMapper.cxx, line 28
Error: no override found for vtkPolyDataMapper`

`Generic Warning: In /home/juliocesar/projects/VTK/Rendering/Core/vtkRenderer.cxx, line 50
Error: no override found for vtkRenderer`

`Segmentation fault (core dumped)`

PD: I haven't tested other tutorial yet, to know if they work properly.

Thank you.

**Comment by SergioRAgostinho** [comment]
Hi. What exactly were the errors before you started adding includes? Which opengl backend are you using in vtk?

**Comment by VictorLamoine** [comment]
You are using catkin_make, which is ROS related, can you test with a simple CMakeLists project?

StackOverflow related questions:
http://stackoverflow.com/questions/18642155/no-override-found-for-vtkpolydatamapper
http://stackoverflow.com/questions/33770279/vtk6-3-link-errorno-override-found-for-vtkrenderwindow

**Comment by jcgarciaca** [comment]
Hi,
Thanks for your help. Without the `include` instructions I get the below message when using `catkin_make` and have `OpenGL version string: 3.0 Mesa 10.1.3`

`CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o: In function `computeCloudResolution(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGBA> const> const&)':
/home/juliocesar/catkin_ws/src/pcl_applications/src/pcl_applications_node.cpp:167: undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::KdTree(bool)'
/home/juliocesar/catkin_ws/src/pcl_applications/src/pcl_applications_node.cpp:168: undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGBA> const> const&, boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o: In function `pcl::Feature<pcl::PointXYZRGBA, pcl::Normal>::initCompute()':
/usr/local/include/pcl-1.8/pcl/features/impl/feature.hpp:123: undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::KdTree(bool)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o: In function `pcl::Feature<pcl::PointXYZRGBA, pcl::SHOT352>::initCompute()':
/usr/local/include/pcl-1.8/pcl/features/impl/feature.hpp:123: undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::KdTree(bool)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o: In function `pcl::Feature<pcl::PointXYZRGBA, pcl::ReferenceFrame>::initCompute()':
/usr/local/include/pcl-1.8/pcl/features/impl/feature.hpp:123: undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::KdTree(bool)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o:(.rodata._ZTVN3pcl15UniformSamplingINS_12PointXYZRGBAEEE[_ZTVN3pcl15UniformSamplingINS_12PointXYZRGBAEEE]+0x24): undefined reference to `pcl::UniformSampling<pcl::PointXYZRGBA>::applyFilter(pcl::PointCloud<pcl::PointXYZRGBA>&)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o:(.rodata._ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE[_ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE]+0x14): undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::setSortedResults(bool)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o:(.rodata._ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE[_ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE]+0x1c): undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGBA> const> const&, boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o:(.rodata._ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE[_ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE]+0x28): undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::nearestKSearch(pcl::PointXYZRGBA const&, int, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&) const'
CMakeFiles/pcl_applications_node.dir/src/pcl_applications_node.cpp.o:(.rodata._ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE[_ZTVN3pcl6search6KdTreeINS_12PointXYZRGBAENS_11KdTreeFLANNIS2_N5flann9L2_SimpleIfEEEEEE]+0x38): undefined reference to `pcl::search::KdTree<pcl::PointXYZRGBA, pcl::KdTreeFLANN<pcl::PointXYZRGBA, flann::L2_Simple<float> > >::radiusSearch(pcl::PointXYZRGBA const&, double, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, unsigned int) const'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/juliocesar/catkin_ws/devel/lib/pcl_applications/pcl_applications_node] Error 1
make[1]: *** [pcl_applications/CMakeFiles/pcl_applications_node.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

To test a simple CMakeLists project should I install [https://cmake.org/download/](url)?

Thank you

**Comment by jcgarciaca** [comment]
I tried with another tutorial [http://pointclouds.org/documentation/tutorials/vfh_recognition.php#vfh-recognition](url), and it shows:

`CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:291 (message):
  catkin_package() absolute include dir '/usr/include/pcl-1.7' does not exist
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  pcl_conversions-indigo-devel/CMakeLists.txt:11 (catkin_package)
`
I removed pcl-1.7 when upgrading to 1.8.

Thank you.

**Comment by stefanbuettner** [comment]
I assume you're using the pre-compiled versions from your OS software repository.
Sounds like your ROS version still depends on PCL 1.7. So did you upgrade ROS as well?
Currently, this feels like a catkin project setup issue rather than an actual pcl problem. Did you try a plain cmake project as it is described in the tutorial? I think, as you're using catkin, cmake is already installed on your system.
