### PR TITLE
outofcore: Explictly use mt19937 random generator for boost 1.67.

### LINKED ISSUE #2284: Fails to build against Boost 1.67
Regressed by https://github.com/boostorg/uuid/commit/a8a1ec3d826b. Found [downstream](https://reviews.freebsd.org/D15030).  CC @yurivict

```c++
$ cmake -GNinja .
$ ninja
[...]
In file included from outofcore/tools/outofcore_print.cpp:53:
In file included from outofcore/include/pcl/outofcore/outofcore_impl.h:50:
outofcore/include/pcl/outofcore/impl/octree_disk_container.hpp:77:74: error: no matching constructor for initialization of 'boost::uuids::random_generator' (aka 'boost::uuids::random_generator_pure')
    boost::uuids::random_generator OutofcoreOctreeDiskContainer<PointT>::uuid_gen_ (&rand_gen_);
                                                                         ^          ~~~~~~~~~~
/usr/local/include/boost/uuid/random_generator.hpp:149:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'boost::mt19937 *' (aka 'mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615U, 11, 4294967295U, 7, 2636928640U, 15, 4022730752U, 18, 1812433253> *') to 'const boost::uuids::random_generator_pure' for 1st argument
class random_generator_pure
      ^
/usr/local/include/boost/uuid/random_generator.hpp:149:7: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
1 error generated.
```

Error logs:
- [FreeBSD 11.1 amd64](http://package22.nyi.freebsd.org/data/111amd64-default-PR227427/2018-04-17_17h22m51s/logs/errors/pcl-pointclouds-1.8.1_2.log)
- [FreeBSD 11.1 i386](http://package23.nyi.freebsd.org/data/111i386-default-PR227427/2018-04-18_09h58m25s/logs/errors/pcl-pointclouds-1.8.1_2.log)
- [FreeBSD 10.3 amd64](http://package22.nyi.freebsd.org/data/103amd64-default-PR227427/2018-04-18_08h05m01s/logs/errors/pcl-pointclouds-1.8.1_2.log)
- [FreeBSD 10.3 i386](http://package23.nyi.freebsd.org/data/103i386-default-PR227427/2018-04-18_08h05m08s/logs/errors/pcl-pointclouds-1.8.1_2.log)

### PR DESCRIPTION
**Pull request by de-vri-es**
This should fix #2284.

Boost 1.67 switched the default `boost::uuid::random_generator` from `boost::uuid::basic_random_generator<boost::mt19937>` to `boost::uuid::random_generator_pure` which uses OS provided randomness.

The new one doesn't accept a PRNG as constructor argument anymore. This PR switches back to the old behaviour explicitly.

It may actually be a good idea to switch to the new behaviour, but that would require some preprocessor checks to stay compatible with boost < 1.67. This PR doesn't change anything, it just chooses the old default explicitly.

Preprocessor checks can be added instead if that has the preference.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Hmm, the test failure seems unrelated?

**Comment by taketwo** [comment]
Yeah, must be something else.

I think just using the old behavior explicitly is good enough for now. We can always add `#ifdefs` and switch to the new behavior if the need arises. Thanks for sending the patch!

**Comment by de-vri-es** [comment]
Thanks for the quick review! :)
