### PR TITLE
Switch between TYPED_TEST_SUITE and TYPED_TEST_CASE depending on gtest version

### PR DESCRIPTION
**Pull request by jammm**
Fixes https://github.com/PointCloudLibrary/pcl/issues/3373

### CODE REVIEW

**Comment by kunaltyagi** [comment]
As @taketwo mentions on the [issue thread](https://github.com/PointCloudLibrary/pcl/issues/3373#issuecomment-535526735), this needs to work with GTest 1.7

Else, it has errors similar to
```
/pcl/test/common/test_common.cpp:311:17: error: expected constructor, destructor, or type conversion before '(' token
 TYPED_TEST_SUITE(XYZPointTypesTest, XYZPointTypes);
                 ^
In file included from /usr/include/gtest/gtest.h:66:0,
                 from /pcl/test/common/test_common.cpp:40:
/pcl/test/common/test_common.cpp:312:1: error: 'gtest_type_params_XYZPointTypesTest_' was not declared in this scope
 TYPED_TEST(XYZPointTypesTest, GetVectorXfMap)
 ^
/pcl/test/common/test_common.cpp:312:1: error: template argument 3 is invalid
 TYPED_TEST(XYZPointTypesTest, GetVectorXfMap)

```

**Comment by taketwo** [comment]
> LGTM

But all CI jobs are broken... :confused:

**Comment by kunaltyagi** [comment]
Ah, I see the problem. The code looks good on surface, but... since pcl_macros.h isn't included everywhere (after gtest header), there are compile errors.

**Comment by jammm** [comment]
> Ah, I see the problem. The code looks good on surface, but... since pcl_macros.h isn't included everywhere (after gtest header), there are compile errors.
> 
> Looks like I was too hasty 😅

My bad, I just noticed it myself as well. Darn you sed!

**Comment by jammm** [comment]
Will squash commits after LGTM's

File: common/include/pcl/pcl_macros.h [hunk 1]
```diff
@@ -369,3 +369,14 @@ aligned_free (void* ptr)
 #else
   #define PCL_NODISCARD
 #endif
+
+/**
+ * \brief Macro choose between TYPED_TEST_CASE and PCL_TYPED_TEST_SUITE depending on the GTest version
+ *
```
Comment (kunaltyagi) [inline common/include/pcl/pcl_macros.h]: Maybe add a note saying that gtest headers needs to be included before `pcl_macros.h`. Or maybe another else in the if-else ladder using a non-existent macro _INCLUDE_GTEST_BEFORE_PCL_MACROS_H_ so that the error messages show the cause

**Comment by kunaltyagi** [comment]
There's one more warning on my setup which seems related (in terms of deprecation cause, but not the same macro):
```
[673/681] Building CXX object test/segmentation/C...s/test_random_walker.dir/test_random_walker.cpp.o
../test/segmentation/test_random_walker.cpp:238:1: warning: 'InstantiateTestCase_P_IsDeprecated' is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Wdeprecated-declarations]
INSTANTIATE_TEST_CASE_P (VariousGraphs,
^
/store/workspace/googletest/googletest/include/gtest/gtest-param-test.h:507:38: note: expanded from macro 'INSTANTIATE_TEST_CASE_P'
  static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
                                     ^
/store/workspace/googletest/googletest/include/gtest/internal/gtest-internal.h:1209:1: note: 'InstantiateTestCase_P_IsDeprecated' has been explicitly marked deprecated here
GTEST_INTERNAL_DEPRECATED(
^
/store/workspace/googletest/googletest/include/gtest/internal/gtest-port.h:2215:59: note: expanded from macro 'GTEST_INTERNAL_DEPRECATED'
#define GTEST_INTERNAL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                          ^
1 warning generated.

```
The offending file is `test/segmentation/test_random_walker.cpp`. Could you please address that here itself since the changes are so correlated?

**Comment by jammm** [comment]
> There's one more warning on my setup which seems related (in terms of deprecation cause, but not the same macro):
> 
> ```
> [673/681] Building CXX object test/segmentation/C...s/test_random_walker.dir/test_random_walker.cpp.o
> ../test/segmentation/test_random_walker.cpp:238:1: warning: 'InstantiateTestCase_P_IsDeprecated' is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Wdeprecated-declarations]
> INSTANTIATE_TEST_CASE_P (VariousGraphs,
> ^
> /store/workspace/googletest/googletest/include/gtest/gtest-param-test.h:507:38: note: expanded from macro 'INSTANTIATE_TEST_CASE_P'
>   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
>                                      ^
> /store/workspace/googletest/googletest/include/gtest/internal/gtest-internal.h:1209:1: note: 'InstantiateTestCase_P_IsDeprecated' has been explicitly marked deprecated here
> GTEST_INTERNAL_DEPRECATED(
> ^
> /store/workspace/googletest/googletest/include/gtest/internal/gtest-port.h:2215:59: note: expanded from macro 'GTEST_INTERNAL_DEPRECATED'
> #define GTEST_INTERNAL_DEPRECATED(message) __attribute__((deprecated(message)))
>                                                           ^
> 1 warning generated.
> ```
> 
> The offending file is `test/segmentation/test_random_walker.cpp`. Could you please address that here itself since the changes are so correlated?

Done. Added another commit to this PR.

File: common/include/pcl/pcl_macros.h (hunk 1 above)
Comment (jammm) [reply common/include/pcl/pcl_macros.h]: How about a #error? Seems more readable source-code wise.

Comment (jammm) [reply common/include/pcl/pcl_macros.h]: NVM. `#error` will cause unexpected compiler errors in places which doesn't require `gtest.h`

Comment (SergioRAgostinho) [reply common/include/pcl/pcl_macros.h]: I'm questioning if defining these macros here is the best option. Since they are test specific I'm tempted to suggest creating a new file inside the `test` folder:
1- You can include gtest headers without issues.
2- These defines are not exposed by us to consumer projects.

Comment (jammm) [reply common/include/pcl/pcl_macros.h]: So having a separate header which can be included within these test files?

Comment (SergioRAgostinho) [reply common/include/pcl/pcl_macros.h]: Yes. Sorry for being unclear. Create a new header inside the tests folder which all test file will include. A suggestion would be creating another `pcl_macros.h`, this one in `pcl/test/include/pcl/test/pcl_macros.h`. Then all test files would include
```cpp
#include <pcl/test/pcl_macros.h>
```
 It's open to suggestions, especially the name of the file, as it is prone to raise confusion.

File: common/include/pcl/pcl_macros.h [hunk 2]
```diff
@@ -370,3 +370,29 @@ aligned_free (void* ptr)
...
+ * \ingroup common
+ */
+#if defined(TYPED_TEST_SUITE)
+  #define PCL_TYPED_TEST_SUITE TYPED_TEST_SUITE
+#elif defined(TYPED_TEST_CASE)
+  #define PCL_TYPED_TEST_SUITE TYPED_TEST_CASE
+#else
+  #define PCL_TYPED_TEST_SUITE PLEASE_INCLUDE_GTEST_H_BEFORE_PCL_MACROS_H
+#endif
```
Comment (SergioRAgostinho) [inline common/include/pcl/pcl_macros.h]: I forgot to mention, that I would rewrite this section (and the next one) as following
```cpp
#if !defined(TYPED_TEST_SUITE)
  #define TYPED_TEST_SUITE TYPED_TEST_CASE
#endif
```

If the user is using an old GTest version, we define the new symbol for him/her/(your preferred pronoun).
And then convert all current uses of `TYPED_TEST_CASE` to the new syntax `TYPED_TEST_SUITE`

File: common/include/pcl/pcl_macros.h (hunk 1 above)
Comment (jammm) [reply common/include/pcl/pcl_macros.h]: The new header name seems fine for me.
@kunaltyagi What do you think?

Comment (kunaltyagi) [reply common/include/pcl/pcl_macros.h]: `<pcl/test/test_macros.h>` is more constrained, but open enough for future.

File: common/include/pcl/pcl_macros.h (hunk 2 above)
Comment (jammm) [reply common/include/pcl/pcl_macros.h]: Done.

File: common/include/pcl/pcl_macros.h (hunk 1 above)
Comment (jammm) [reply common/include/pcl/pcl_macros.h]: Done. Waiting for the tests to run.

File: test/common/test_type_traits.cpp [hunk 3]
```diff
@@ -36,11 +36,11 @@
  */
 
 
-#include <pcl/pcl_macros.h>
 #include <pcl/point_traits.h>
 #include <pcl/point_types.h>
 
 #include <gtest/gtest.h>
+#include <pcl/test/pcl_macros.h>
```
Comment (SergioRAgostinho) [inline test/common/test_type_traits.cpp]: Our header grouping strategy, when it is enforced, packs together headers from the same project. In this situation just leave it where it was.

File: test/include/pcl/test/pcl_macros.h [hunk 4]
```diff
@@ -0,0 +1,62 @@
+/*
+ * Software License Agreement (BSD License)
+ *
+ *  Point Cloud Library (PCL) - www.pointclouds.org
+ *  Copyright (c) 2010-2012, Willow Garage, Inc.
```
Comment (SergioRAgostinho) [inline test/include/pcl/test/pcl_macros.h]: Copyright is 2019 onward in this situation and it it attributed to Open Perception. Here's an up-to-date example
https://github.com/PointCloudLibrary/pcl/blob/f5997d30ac7a4827c9b70895fdd5cb0f39df872f/common/include/pcl/make_shared.h#L5

File: test/include/pcl/test/pcl_macros.h [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+#endif
+
+/**
+ * \brief Macro choose between INSTANTIATE_TEST_CASE_P and INSTANTIATE_TEST_SUITE_P depending on the GTest version
+ *
+ * \ingroup test
+ */
+#if !defined(INSTANTIATE_TEST_SUITE_P)
+  #define INSTANTIATE_TEST_SUITE_P INSTANTIATE_TEST_CASE_P
+#endif
```
Comment (SergioRAgostinho) [inline test/include/pcl/test/pcl_macros.h]: Insert a new line at the end of the file.

File: test/octree/test_octree_iterator.cpp [hunk 6]
```diff
@@ -35,12 +35,14 @@
  *
  *
  */
+#include <pcl/pcl_macros.h>
```
Comment (SergioRAgostinho) [inline test/octree/test_octree_iterator.cpp]: You should be able to remove this now.

**Comment by jammm** [comment]
I'll get back to this once I am free (currently working on a separate project on a deadline)
