### ISSUE TITLE
OpenMP linking errors in 1.11.0 release on Ubuntu 16.04

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4235]
I just downloaded the 1.11.0 release and attempt to compile in on Ubuntu 16.04.

**Steps to reproduce**

- Fetch https://github.com/PointCloudLibrary/pcl/archive/pcl-1.11.0.tar.gz
- run `cmake` then `make`
- Obtain errors: 

```
…
[ 18%] Linking CXX executable ../../bin/pcl_pcd_introduce_nan
../../lib/libpcl_common.so.1.11.0: undefined reference to `__kmpc_for_static_fini'
../../lib/libpcl_common.so.1.11.0: undefined reference to `__kmpc_for_static_init_4'
../../lib/libpcl_common.so.1.11.0: undefined reference to `__kmpc_fork_call'
```

I have OpenMP installed and the CMake output is

```
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE ClangFormat_VERSION) (Required is at least version "10")
-- Using CPU native flags for SSE optimization: -march=native
-- Found OpenMP_C: -fopenmp=libomp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE  found components:  C CXX
-- Found OpenMP, spec date 201307
-- Eigen found (include: /usr/local/include/eigen3, version: 3.3.7)
-- Could NOT find LIBUSB_1 (missing: LIBUSB_1_LIBRARY LIBUSB_1_INCLUDE_DIR)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- Could NOT find Qhull (missing: QHULL_LIBRARIES QHULL_INCLUDE_DIRS)
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- VTK_MAJOR_VERSION 6, rendering backend: OpenGL
-- VTK found (include: /usr/include/vtk-6.2;/usr/include/freetype2;/usr/include/x86_64-linux-gnu/freetype2;/usr/include;/usr/include/x86_64-linux-gnu;/usr/include/jsoncpp, libs: vtkChartsCore;vtkCommonColor;vtkCommonDataModel;vtkCommonMath;vtkCommonCore;vtksys;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkInfovisCore;vtkFiltersExtraction;vtkCommonExecutionModel;vtkFiltersCore;vtkFiltersGeneral;vtkCommonComputationalGeometry;vtkFiltersStatistics;vtkImagingFourier;vtkImagingCore;vtkalglib;vtkRenderingContext2D;vtkRenderingCore;vtkFiltersGeometry;vtkFiltersSources;vtkRenderingFreeType;/usr/lib/x86_64-linux-gnu/libfreetype.so;/usr/lib/x86_64-linux-gnu/libz.so;vtkftgl;vtkFiltersModeling;vtkImagingSources;vtkInteractionStyle;vtkInteractionWidgets;vtkFiltersHybrid;vtkImagingGeneral;vtkImagingHybrid;vtkIOImage;vtkDICOMParser;vtkIOCore;vtkmetaio;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libtiff.so;vtkRenderingAnnotation;vtkImagingColor;vtkRenderingVolume;vtkIOGeometry;/usr/lib/x86_64-linux-gnu/libjsoncpp.so;vtkIOLegacy;vtkIOPLY;vtkRenderingLOD;vtkViewsContext2D;vtkViewsCore;vtkRenderingContextOpenGL;vtkRenderingOpenGL;vtkRenderingQt;vtkFiltersTexture;vtkGUISupportQt;vtkRenderingLabel
CMake Deprecation Warning at CMakeLists.txt:427 (message):
  The rendering backend OpenGL is deprecated and not available anymore since
  VTK 8.2.Please switch to the OpenGL2 backend instead, which is available
  since VTK 6.2.Support of the deprecated backend will be dropped with PCL
  1.13.


-- Could NOT find PCAP (missing: PCAP_LIBRARIES PCAP_INCLUDE_DIRS)
-- Could NOT find GLEW (missing: GLEW_INCLUDE_DIRS GLEW_LIBRARIES)
-- DOXYGEN_FOUND
-- HTML_HELP_COMPILER
-- Found CPack generators: DEB
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   visualization
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   outofcore
--   people
--   tools
-- The following subsystems will not be built:
--   apps: Disabled by default
--   examples: Code examples are disabled by default.
--   simulation: Disabled by default.
--   global_tests: Disabled by default
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/pcl-pcl-1.11.0/build
```

There seem to be dependency issues which the CMake script does not pick up.

**Comment by themightyoarfish** [comment]
Not sure if related, but when disabling OpenMP, my build instead fails with 
```
Linking CXX executable ../../bin/pcl_outofcore_viewer
/usr/bin/ld: CMakeFiles/pcl_outofcore_viewer.dir/__/src/visualization/outofcore_cloud.cpp.o: undefined reference to symbol 'pthread_rwlock_unlock@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by themightyoarfish** [comment]
The latter I can fix with manually adding `-lpthread` to the linker flags manually, but I haven't figured out where to place it in the CMakeLists to have it appear at the end of the compiler invocation (beginning seems to not work).
I tried `add_definitions()` and `CMAKE_EXE_LINKER_FLAGS` with `-lpthread`, but it doesn't seem to affect `pcl_outofcore_viewer` target.

**Comment by SergioRAgostinho** [comment]
Probably something along these lines
https://github.com/PointCloudLibrary/pcl/blob/e6d032a1eed0115542ae9895679b75a5fca06eef/cmake/pcl_targets.cmake#L227-L229

For older CMake versions, that target might not exist.

**Comment by themightyoarfish** [comment]
Where do you propose to put this? The file you linked is present already in that version. I'm using relatively recent cmake 3.15.

**Comment by SergioRAgostinho** [comment]
Sorry, I misunderstood. It kinda suggests OMP is adding those flags in the background and once disabled they're no longer being added. Check if pcl_outofcore declares Threads::Threads as a dependency, if not add it.

**Comment by elfprince13** [comment]
This also fails on Ubuntu 18.04.

**Comment by elfprince13** [comment]
Some debugging suggests it may be a compiler issue?

Using verbose makefiles I discovered CMake was using the default system c++:
 > c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I could get it to compile by copying the command line from the verbose makefile and appending `-lomp5` (although adding `-lomp5` to the `CMAKE_CXX_COMPILER_FLAGS` did not help.

On the other hand, if I rebuild with `CMAKE_CXX_COMPILER=clang++`, everything works fine out of the box.

**Comment by themightyoarfish** [comment]
Has there been any new development on this? Am I  wrong in thinking openmp does not work on most systems, if ubuntu 18.04 is alco affected?

**Comment by kunaltyagi** [comment]
Works on 20.04 (also reported working with clang), so might be a compiler configuration issue.
