### PR TITLE
Compilation errors related to symmetric ICP objective

### LINKED ISSUE #3462: Compilation error related to symmetric ICP objective
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7.4
* PCL Version: master

Got the following error compiling a downstream project with the fresh master:

```cpp
/usr/local/include/pcl-1.9/pcl/registration/icp.h:347:13: error: no matching function for call to ‘boost::shared_ptr<pcl::registration::TransformationEstimation<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal, double> >::reset(boost::shared_ptr<pcl::registration::TransformationEstimationSymmetricPointToPlaneLLS<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal, double> >&)’
             transformation_estimation_.reset (symmetric_transformation_estimation);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is clearly caused by #3390. The problem and the fix are obvious, but what needs to be checked is how this escaped surfacing during unit tests.

### PR DESCRIPTION
**Pull request by taketwo**
This PR fixes the compilation error reported in #3462 and a further (unreported) error that happens when the symmetric objective is instantiated with `double` precision.

Fixes #3462.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Maybe we can add dummy tests to just compile these classes (and do nothing else)
