### ISSUE TITLE
[gpu] CUDA 13.2 build fails

### ISSUE THREAD

**Issue by jmackay2** [PointCloudLibrary/pcl#6423]
**Describe the bug**

When upgrading from cuda 13.1 to 13.2, building PCL fails with the following error:
```
pcl/gpu/utils/include/pcl/gpu/utils/device/functional.hpp(89): error: namespace "cuda::std" has no member "identity"
    using cuda::std::identity
```

**Context**
- OS: Ubuntu 24.04
- PCL version: latest master branch
- CUDA version: 13.2

**Expected behavior**

Successful build.

**Current Behavior**

Above error.

**To Reproduce**

Build PCL with CUDA and the GPU module on CUDA 13.2. 

**Possible Solution**

Handle another CUDA version check where `std::identity` is used for newer versions.
