### ISSUE TITLE
Build error on OSX

### ISSUE THREAD

**Issue by dpo** [PointCloudLibrary/pcl#1556]
I'm trying to build PCL against VTK7 using the Homebrew formula. I'm getting a build error:
```
[ 22%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/histogram_visualizer.cpp.o
cd /tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/macbuild/visualization && /usr/local/Library/ENV/4.3/clang++   -DEIGEN_USE_NEW_STDVECTOR -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET -DPCLAPI_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -Dqh_QHpointer -DvtkDomainsChemistry_AUTOINIT="1(vtkDomainsChemistryOpenGL2)" -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -DvtkRenderingFreeType_AUTOINIT="1(vtkRenderingFreeTypeFontConfig)" -DvtkRenderingVolume_AUTOINIT="1(vtkRenderingVolumeOpenGL2)" -isystem /usr/local/include -isystem /usr/local/include/eigen3 -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/recognition/include/pcl/recognition/3rdparty -isystem /usr/local/Cellar/qt/4.8.7_2/include -iframework /usr/local/Cellar/qt/4.8.7_2/lib -isystem /usr/local/Cellar/qt/4.8.7_2/include/QtGui -isystem /usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Headers -I/usr/local/Cellar/vtk/7.0.0/include/vtk-7.0 -I/usr/local/Cellar/open-mpi/1.10.1_1/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/include/libxml2 -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/macbuild/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/visualization/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/common/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/io/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/kdtree/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/geometry/include -I/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/search/include  -ftemplate-depth=1024 -Qunused-arguments -Wno-invalid-offsetof   -DNDEBUG -fPIC   -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -o CMakeFiles/pcl_visualization.dir/src/histogram_visualizer.cpp.o -c /tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/visualization/src/histogram_visualizer.cpp
/tmp/pcl20160227-70108-1sk0fb3/pcl-pcl-1.7.2/visualization/src/pcl_visualizer.cpp:59:10: fatal error: 'vtkVisibleCellSelector.h' file not found
#include <vtkVisibleCellSelector.h>
```
Apparently, `vtkVisibleCellSelector.h` wasn't installed by VTK. Do I need to build VTK with specific options?

Thanks.

**Comment by r9y9** [comment]
OpenGL2 backend for VTK (which is the default of VTK7) is known to not work with PCL 1.7 (specifically, without https://github.com/PointCloudLibrary/pcl/pull/1534). Not sure if PCL 1.7 can be built with VTK7 but I guess you can try OpenGL backend instead of OpenGL2. If you have chance to get PCL trunk, you can use OpenGL2 backend as well.

**Comment by VictorLamoine** [comment]
Already fixed with https://github.com/PointCloudLibrary/pcl/pull/1500

**Comment by dpo** [comment]
Thanks. I'm able to build `master`, but I can't build release 1.7.2 with the patches that you give. Applying only #1534 or only #1500 results in
```
/tmp/pcl20160228-19937-y53ufu/pcl-pcl-1.7.2/visualization/src/pcl_visualizer.cpp:88:10: fatal error: 'vtkOpenGLHardwareSupport.h' file not found
#include <vtkOpenGLHardwareSupport.h>
         ^
```
Applying both results in patch conflicts.

**Comment by VictorLamoine** [comment]
There must be inter-commits between  #1500  and #1534 editing these specific files / lines, thus the conflict.

You have to track all the changes between #1500 and #1524 in these files and make sure to apply the modifications.
I wouldn't bother and use master `instead`, it's really not "less stable" than 1.7.2 release.
