### ISSUE TITLE
Fails to build with Boost 1.70 (Beta1)

### ISSUE THREAD

**Issue by jbeich** [PointCloudLibrary/pcl#2931]
Regressed by boostorg/core@d8895bab4676:
```c++
In file included from segmentation/src/supervoxel_clustering.cpp:49:
In file included from segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:43:
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: error: 'checked_delete<const
      pcl::SupervoxelClustering<pcl::PointXYZRGB>::SupervoxelHelper>' is missing exception specification
      'noexcept'
  ...boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
            ^
                                                                                                    noexcept
segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:704:75: note: in instantiation of template
      class 'pcl::SupervoxelClustering<pcl::PointXYZRGB>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGB,pcl::SupervoxelClustering<pcl::PointX...
                                                                          ^
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: error: 'checked_delete<const
      pcl::SupervoxelClustering<pcl::PointXYZRGBA>::SupervoxelHelper>' is missing exception specification
      'noexcept'
  ...boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
            ^
                                                                                                    noexcept
segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:708:76: note: in instantiation of template
      class 'pcl::SupervoxelClustering<pcl::PointXYZRGBA>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGBA,pcl::SupervoxelClustering<pcl::Point...
                                                                           ^
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: error: 'checked_delete<const
      pcl::SupervoxelClustering<pcl::PointXYZ>::SupervoxelHelper>' is missing exception specification 'noexcept'
  ...boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
            ^
                                                                                                    noexcept
segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp:720:72: note: in instantiation of template
      class 'pcl::SupervoxelClustering<pcl::PointXYZ>' requested here
    pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZ,pcl::SupervoxelClustering<pcl::PointXYZ>...
                                                                       ^
segmentation/include/pcl/segmentation/supervoxel_clustering.h:527:26: note: previous declaration is here
      friend void boost::checked_delete<> (const typename pcl::SupervoxelClustering<PointT>::SupervoxelHelper *);
                         ^
3 errors generated.
```

**Comment by taketwo** [comment]
Hi, please try if this patch solves the problem: [patch.txt](https://github.com/PointCloudLibrary/pcl/files/2975614/patch.txt)

**Comment by jbeich** [comment]
@taketwo, I confirm, the patch fixes build.

**Comment by taketwo** [comment]
Thanks for reporting and testing. I will make a PR tomorrow.
