### ISSUE TITLE
[compile error] Couldn't compile on Ubuntu 16.04 with BUILD_surface_on_nurbs set to on and PCL_ENABLE_SSE set to off

### ISSUE THREAD

**Issue by madhan001** [PointCloudLibrary/pcl#4285]
<details><summary>CMake Log</summary>

```cpp
[ 87%] Building CXX object people/CMakeFiles/pcl_ground_based_rgbd_people_detector.dir/apps/main_ground_based_people_detection.cpp.o
In file included from /home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/gicp.h:45:0,
                 from /home/madhan/Downloads/pcl-pcl-1.9.1/registration/src/gicp.cpp:40:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:9: error: ‘PolynomialSolver’ is not a class template
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
         ^~~~~~~~~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:66: error: expected template-name before ‘<’ token
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
                                                                  ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:66: error: expected ‘{’ before ‘<’ token
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h: In member function ‘void BFGS<FunctorType>::checkExtremum(const Eigen::Matrix<typename FunctorType::Scalar, 4, 1>&, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar&, BFGS<FunctorType>::Scalar&)’:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:199:21: error: ‘poly_eval’ is not a member of ‘Eigen’
   Scalar y = Eigen::poly_eval(coefficients, x);
                     ^~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h: In member function ‘BFGS<FunctorType>::Scalar BFGS<FunctorType>::interpolate(BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, int)’:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:454:19: error: ‘poly_eval’ is not a member of ‘Eigen’
     fmin = Eigen::poly_eval (coefficients, ymin);
                   ^~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:461:40: error: wrong number of template arguments (2, should be 1)
       Eigen::PolynomialSolver<Scalar, 2> solver (coefficients2, real_roots);
                                        ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:35: note: provided for ‘template<class _Scalar> class Eigen::PolynomialSolver’
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
                                   ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:461:75: error: expression list treated as compound expression in initializer [-fpermissive]
       Eigen::PolynomialSolver<Scalar, 2> solver (coefficients2, real_roots);
                                                                           ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:464:21: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
         if ((solver.roots ()).size () == 2)  /* found 2 roots */
                     ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:466:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y0 = std::real (solver.roots () [0]);
                                  ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:467:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y1 = std::real (solver.roots () [1]);
                                  ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:474:26: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
         else if ((solver.roots ()).size () == 1)  /* found 1 root */
                          ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:476:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y0 = std::real (solver.roots () [0]);
                                  ^~~~~
In file included from /home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/gicp.h:45:0,
                 from /home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/gicp6d.h:46,
                 from /home/madhan/Downloads/pcl-pcl-1.9.1/registration/src/gicp6d.cpp:39:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:9: error: ‘PolynomialSolver’ is not a class template
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
         ^~~~~~~~~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:66: error: expected template-name before ‘<’ token
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
                                                                  ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:66: error: expected ‘{’ before ‘<’ token
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h: In member function ‘void BFGS<FunctorType>::checkExtremum(const Eigen::Matrix<typename FunctorType::Scalar, 4, 1>&, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar&, BFGS<FunctorType>::Scalar&)’:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:199:21: error: ‘poly_eval’ is not a member of ‘Eigen’
   Scalar y = Eigen::poly_eval(coefficients, x);
                     ^~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h: In member function ‘BFGS<FunctorType>::Scalar BFGS<FunctorType>::interpolate(BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, BFGS<FunctorType>::Scalar, int)’:
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:454:19: error: ‘poly_eval’ is not a member of ‘Eigen’
     fmin = Eigen::poly_eval (coefficients, ymin);
                   ^~~~~~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:461:40: error: wrong number of template arguments (2, should be 1)
       Eigen::PolynomialSolver<Scalar, 2> solver (coefficients2, real_roots);
                                        ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:13:35: note: provided for ‘template<class _Scalar> class Eigen::PolynomialSolver’
   class PolynomialSolver<_Scalar,2> : public PolynomialSolverBase<_Scalar,2>
                                   ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:461:75: error: expression list treated as compound expression in initializer [-fpermissive]
       Eigen::PolynomialSolver<Scalar, 2> solver (coefficients2, real_roots);
                                                                           ^
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:464:21: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
         if ((solver.roots ()).size () == 2)  /* found 2 roots */
                     ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:466:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y0 = std::real (solver.roots () [0]);
                                  ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:467:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y1 = std::real (solver.roots () [1]);
                                  ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:474:26: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
         else if ((solver.roots ()).size () == 1)  /* found 1 root */
                          ^~~~~
/home/madhan/Downloads/pcl-pcl-1.9.1/registration/include/pcl/registration/bfgs.h:476:34: error: request for member ‘roots’ in ‘solver’, which is of non-class type ‘int’
           y0 = std::real (solver.roots () [0]);
                                  ^~~~~
registration/CMakeFiles/pcl_registration.dir/build.make:590: recipe for target 'registration/CMakeFiles/pcl_registration.dir/src/gicp.cpp.o' failed
make[2]: *** [registration/CMakeFiles/pcl_registration.dir/src/gicp.cpp.o] Error 1
```
</details>

**Your Environment (please complete the following information):**

 - OS: Ubuntu 16.04
 - Compiler:  GCC 7.5
 - PCL Version 1.9.1
 - PCL Type: Compiled

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes
 - List and Version of dependencies used
 - Compilation flags are used
BUILD_surface_on_nurbs = ON
PCL_ENABLE_SSE = OFF

**Comment by shrijitsingh99** [comment]
Could you try and report the result with GPU & CUDA module disabled.

**Comment by madhan001** [comment]
> Could you try and report the result with GPU & CUDA module disabled.

I did try with with CUDA and the nvidia GPU disabled but had the same error even with 1.11, anyway I decided to go with a clean install of Ubuntu 16.04 and it worked even with the GPU and CUDA enabled.

**Comment by kunaltyagi** [comment]
If the issue was with your system configuration, please close the issue
