### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by suk8267** [PointCloudLibrary/pcl#3592]
when i follow icp code in pcl webpage, i got some error.

this is my code and my cmakefile.
```
#include <iostream>
#include <string>

#include <pcl/io/ply_io.h>
#include <pcl/point_types.h>
#include <pcl/registration/icp.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/console/time.h>   // TicToc

typedef pcl::PointXYZ PointT;
typedef pcl::PointCloud<PointT> PointCloudT;

bool next_iteration = false;

void
print4x4Matrix (const Eigen::Matrix4d & matrix)
{
  printf ("Rotation matrix :\n");
  printf ("    | %6.3f %6.3f %6.3f | \n", matrix (0, 0), matrix (0, 1), matrix (0, 2));
  printf ("R = | %6.3f %6.3f %6.3f | \n", matrix (1, 0), matrix (1, 1), matrix (1, 2));
  printf ("    | %6.3f %6.3f %6.3f | \n", matrix (2, 0), matrix (2, 1), matrix (2, 2));
  printf ("Translation vector :\n");
  printf ("t = < %6.3f, %6.3f, %6.3f >\n\n", matrix (0, 3), matrix (1, 3), matrix (2, 3));
}

void
keyboardEventOccurred (const pcl::visualization::KeyboardEvent& event,
                       void* nothing)
{
  if (event.getKeySym () == "space" && event.keyDown ())
    next_iteration = true;
}

int
main (int argc,
      char* argv[])
{
  // The point clouds we will be using
  PointCloudT::Ptr cloud_in (new PointCloudT);  // Original point cloud
  PointCloudT::Ptr cloud_tr (new PointCloudT);  // Transformed point cloud
  PointCloudT::Ptr cloud_icp (new PointCloudT);  // ICP output point cloud

  // Checking program arguments
  if (argc < 2)
  {
    printf ("Usage :\n");
    printf ("\t\t%s file.ply number_of_ICP_iterations\n", argv[0]);
    PCL_ERROR ("Provide one ply file.\n");
    return (-1);
  }

  int iterations = 1;  // Default number of ICP iterations
  if (argc > 2)
  {
    // If the user passed the number of iteration as an argument
    iterations = atoi (argv[2]);
    if (iterations < 1)
    {
      PCL_ERROR ("Number of initial iterations must be >= 1\n");
      return (-1);
    }
  }

  pcl::console::TicToc time;
  time.tic ();
  if (pcl::io::loadPLYFile (argv[1], *cloud_in) < 0)
  {
    PCL_ERROR ("Error loading cloud %s.\n", argv[1]);
    return (-1);
  }
  std::cout << "\nLoaded file " << argv[1] << " (" << cloud_in->size () << " points) in " << time.toc () << " ms\n" << std::endl;

  // Defining a rotation matrix and translation vector
  Eigen::Matrix4d transformation_matrix = Eigen::Matrix4d::Identity ();

  // A rotation matrix (see https://en.wikipedia.org/wiki/Rotation_matrix)
  double theta = M_PI / 8;  // The angle of rotation in radians
  transformation_matrix (0, 0) = std::cos (theta);
  transformation_matrix (0, 1) = -sin (theta);
  transformation_matrix (1, 0) = sin (theta);
  transformation_matrix (1, 1) = std::cos (theta);

  // A translation on Z axis (0.4 meters)
  transformation_matrix (2, 3) = 0.4;

  // Display in terminal the transformation matrix
  std::cout << "Applying this rigid transformation to: cloud_in -> cloud_icp" << std::endl;
  print4x4Matrix (transformation_matrix);

  // Executing the transformation
  pcl::transformPointCloud (*cloud_in, *cloud_icp, transformation_matrix);
  *cloud_tr = *cloud_icp;  // We backup cloud_icp into cloud_tr for later use

  // The Iterative Closest Point algorithm
  time.tic ();
  pcl::IterativeClosestPoint<PointT, PointT> icp;
  icp.setMaximumIterations (iterations);
  icp.setInputSource (cloud_icp);
  icp.setInputTarget (cloud_in);
  icp.align (*cloud_icp);
  icp.setMaximumIterations (1);  // We set this variable to 1 for the next time we will call .align () function
  std::cout << "Applied " << iterations << " ICP iteration(s) in " << time.toc () << " ms" << std::endl;

  if (icp.hasConverged ())
  {
    std::cout << "\nICP has converged, score is " << icp.getFitnessScore () << std::endl;
    std::cout << "\nICP transformation " << iterations << " : cloud_icp -> cloud_in" << std::endl;
    transformation_matrix = icp.getFinalTransformation ().cast<double>();
    print4x4Matrix (transformation_matrix);
  }
  else
  {
    PCL_ERROR ("\nICP has not converged.\n");
    return (-1);
  }

  // Visualization
  pcl::visualization::PCLVisualizer viewer ("ICP demo");
  // Create two vertically separated viewports
  int v1 (0);
  int v2 (1);
  viewer.createViewPort (0.0, 0.0, 0.5, 1.0, v1);
  viewer.createViewPort (0.5, 0.0, 1.0, 1.0, v2);

  // The color we will be using
  float bckgr_gray_level = 0.0;  // Black
  float txt_gray_lvl = 1.0 - bckgr_gray_level;

  // Original point cloud is white
  pcl::visualization::PointCloudColorHandlerCustom<PointT> cloud_in_color_h (cloud_in, (int) 255 * txt_gray_lvl, (int) 255 * txt_gray_lvl,
                                                                             (int) 255 * txt_gray_lvl);
  viewer.addPointCloud (cloud_in, cloud_in_color_h, "cloud_in_v1", v1);
  viewer.addPointCloud (cloud_in, cloud_in_color_h, "cloud_in_v2", v2);

  // Transformed point cloud is green
  pcl::visualization::PointCloudColorHandlerCustom<PointT> cloud_tr_color_h (cloud_tr, 20, 180, 20);
  viewer.addPointCloud (cloud_tr, cloud_tr_color_h, "cloud_tr_v1", v1);

  // ICP aligned point cloud is red
  pcl::visualization::PointCloudColorHandlerCustom<PointT> cloud_icp_color_h (cloud_icp, 180, 20, 20);
  viewer.addPointCloud (cloud_icp, cloud_icp_color_h, "cloud_icp_v2", v2);

  // Adding text descriptions in each viewport
  viewer.addText ("White: Original point cloud\nGreen: Matrix transformed point cloud", 10, 15, 16, txt_gray_lvl, txt_gray_lvl, txt_gray_lvl, "icp_info_1", v1);
  viewer.addText ("White: Original point cloud\nRed: ICP aligned point cloud", 10, 15, 16, txt_gray_lvl, txt_gray_lvl, txt_gray_lvl, "icp_info_2", v2);

  std::stringstream ss;
  ss << iterations;
  std::string iterations_cnt = "ICP iterations = " + ss.str ();
  viewer.addText (iterations_cnt, 10, 60, 16, txt_gray_lvl, txt_gray_lvl, txt_gray_lvl, "iterations_cnt", v2);

  // Set background color
  viewer.setBackgroundColor (bckgr_gray_level, bckgr_gray_level, bckgr_gray_level, v1);
  viewer.setBackgroundColor (bckgr_gray_level, bckgr_gray_level, bckgr_gray_level, v2);

  // Set camera position and orientation
  viewer.setCameraPosition (-3.68332, 2.94092, 5.71266, 0.289847, 0.921947, -0.256907, 0);
  viewer.setSize (1280, 1024);  // Visualiser window size

  // Register keyboard callback :
  viewer.registerKeyboardCallback (&keyboardEventOccurred, (void*) NULL);

  // Display the visualiser
  while (!viewer.wasStopped ())
  {
    viewer.spinOnce ();

    // The user pressed "space" :
    if (next_iteration)
    {
      // The Iterative Closest Point algorithm
      time.tic ();
      icp.align (*cloud_icp);
      std::cout << "Applied 1 ICP iteration in " << time.toc () << " ms" << std::endl;

      if (icp.hasConverged ())
      {
        printf ("\033[11A");  // Go up 11 lines in terminal output.
        printf ("\nICP has converged, score is %+.0e\n", icp.getFitnessScore ());
        std::cout << "\nICP transformation " << ++iterations << " : cloud_icp -> cloud_in" << std::endl;
        transformation_matrix *= icp.getFinalTransformation ().cast<double>();  // WARNING /!\ This is not accurate! For "educational" purpose only!
        print4x4Matrix (transformation_matrix);  // Print the transformation between original pose and current pose

        ss.str ("");
        ss << iterations;
        std::string iterations_cnt = "ICP iterations = " + ss.str ();
        viewer.updateText (iterations_cnt, 10, 60, 16, txt_gray_lvl, txt_gray_lvl, txt_gray_lvl, "iterations_cnt");
        viewer.updatePointCloud (cloud_icp, cloud_icp_color_h, "cloud_icp_v2");
      }
      else
      {
        PCL_ERROR ("\nICP has not converged.\n");
        return (-1);
      }
    }
    next_iteration = false;
  }
  return (0);
}
```

CMakeList.txt
```cmake
cmake_minimum_required (VERSION 2.6 FATAL_ERROR)

project(Tutorial)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(PCL 1.5 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})

link_directories(${PCL_LIBRARY_DIRS})

add_definitions(${PCL_DEFINITIONS})

add_executable(Tutorial tutorial.cpp)

target_link_libraries(Tutorial ${PCL_LIBRARIES})
```

and this is my error
```
CMakeFiles/Tutorial.dir/tutorial.cpp.o: In function `pcl::visualization::PCLVisualizer::registerKeyboardCallback(void (*)(pcl::visualization::KeyboardEvent const&, void*), void*)':
tutorial.cpp:(.text._ZN3pcl13visualization13PCLVisualizer24registerKeyboardCallbackEPFvRKNS0_13KeyboardEventEPvES5_[_ZN3pcl13visualization13PCLVisualizer24registerKeyboardCallbackEPFvRKNS0_13KeyboardEventEPvES5_]+0x5e): undefined reference to `pcl::visualization::PCLVisualizer::registerKeyboardCallback(std::function<void (pcl::visualization::KeyboardEvent const&)>)'
collect2: error: ld returned 1 exit status
CMakeFiles/Tutorial.dir/build.make:193: recipe for target 'Tutorial' failed
make[2]: *** [Tutorial] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Tutorial.dir/all' failed
make[1]: *** [CMakeFiles/Tutorial.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
i don't know why this happen please help me.

thank you.

**Comment by kunaltyagi** [comment]
The key hint is `undefined reference to `pcl::visualization::PCLVisualizer::registerKeyboardCallback` which implies:
* no issues with compilation
* issue with linking

So, probably PCL isn't compiled with visualization on your system or you're using an old PCL and the relevant library isn't linked properly for some reason (1.5 as stated in the CMake)

**Comment by suk8267** [comment]
@kunaltyagi hmm i don't know about visualization.. how can i compile visualization?

**Comment by kunaltyagi** [comment]
I'm sorry, but I can't help on PCL 1.5. Are you sure you're using PCL 1.5 and not a more modern version? Could you please have a `message(STATUS ${PCL_LIBRARIES})` in CMake to see which libraries are being linked?

**Comment by suk8267** [comment]
@kunaltyagi ah. i am using pcl 1.7.2 version..

**Comment by taketwo** [comment]
The issue is most likely due to mismatch between the PCL version you are using and the tutorial version that is online. The latter is compatible with the most up-to-date PCL (i.e. 1.10.0 as of today), but will not necessarily work with 1.7.2 due to API changes that happened since then. You have two options:
1) Switch to latest PCL and use the tutorial code from the webpage.
2) Stay with old PCL and get matching tutorial code. This you can find in the repository under corresponding tag: https://github.com/PointCloudLibrary/pcl/tree/pcl-1.7.2/doc/tutorials/content/sources/interactive_icp

**Comment by suk8267** [comment]
@taketwo sorry, i saw it now. u say that 1.10.0 version is latest version?

but i followed http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php     this site. so i think this is the latest version.

so i will follow option 2 and i will apprise you. thank you

**Comment by suk8267** [comment]
and i followed option 2, but nothing be changed... i get same error.

**Comment by kunaltyagi** [comment]
What's the CMake output? Does it contain the following lines:
```
-- looking for PCL_VISUALIZATION
-- Found PCL_VISUALIZATION: /something/libpcl_visualization.so 
```

Or else please proviide the value of `PCL_LIBRARIES` as asked above. Please note that the CI setup has succeeded implying the code is correct for PCL compiled from source.

**Comment by suk8267** [comment]
CMake output is

-- Eigen found (include: /usr/include/eigen3, version: 3.2.92)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   iostreams
--   serialization
--   regex
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
-- QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- looking for PCL_COMMON
-- looking for PCL_KDTREE
-- looking for PCL_OCTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_2D
-- looking for PCL_FEATURES
-- looking for PCL_IO
-- looking for PCL_GEOMETRY
-- looking for PCL_VISUALIZATION
-- looking for PCL_ML
-- looking for PCL_SEGMENTATION
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_KEYPOINTS
-- looking for PCL_OUTOFCORE
-- looking for PCL_STEREO
-- looking for PCL_SURFACE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_APPS
-- pcl_commonpcl_kdtreepcl_octreepcl_searchpcl_sample_consensuspcl_filterspcl_featurespcl_iopcl_visualizationpcl_mlpcl_segmentationpcl_peoplepcl_trackingpcl_keypointspcl_outofcorepcl_stereopcl_surfacepcl_registrationpcl_recognitionpcl_apps/usr/lib/x86_64-linux-gnu/libboost_system.so/usr/lib/x86_64-linux-gnu/libboost_filesystem.so/usr/lib/x86_64-linux-gnu/libboost_date_time.so/usr/lib/x86_64-linux-gnu/libboost_iostreams.so/usr/lib/x86_64-linux-gnu/libboost_serialization.so/usr/lib/x86_64-linux-gnu/libboost_regex.sooptimized/usr/lib/x86_64-linux-gnu/libqhull.sodebug/usr/lib/x86_64-linux-gnu/libqhull.so/usr/lib/libOpenNI.so/usr/lib/libOpenNI2.sovtkChartsCorevtkCommonColorvtkCommonDataModelvtkCommonMathvtkCommonCorevtksysvtkCommonMiscvtkCommonSystemvtkCommonTransformsvtkInfovisCorevtkFiltersExtractionvtkCommonExecutionModelvtkFiltersCorevtkFiltersGeneralvtkCommonComputationalGeometryvtkFiltersStatisticsvtkImagingFouriervtkImagingCorevtkalglibvtkRenderingContext2DvtkRenderingCorevtkFiltersGeometryvtkFiltersSourcesvtkRenderingFreeType/usr/lib/x86_64-linux-gnu/libfreetype.so/usr/lib/x86_64-linux-gnu/libz.sovtkftglvtkFiltersModelingvtkImagingSourcesvtkInteractionStylevtkInteractionWidgetsvtkFiltersHybridvtkImagingGeneralvtkImagingHybridvtkIOImagevtkDICOMParservtkIOCorevtkmetaio/usr/lib/x86_64-linux-gnu/libjpeg.so/usr/lib/x86_64-linux-gnu/libpng.so/usr/lib/x86_64-linux-gnu/libtiff.sovtkRenderingAnnotationvtkImagingColorvtkRenderingVolumevtkIOGeometry/usr/lib/x86_64-linux-gnu/libjsoncpp.sovtkIOLegacyvtkIOPLYvtkRenderingLODvtkViewsContext2DvtkViewsCorevtkRenderingContextOpenGLvtkRenderingOpenGLvtkRenderingQtvtkFiltersTexturevtkGUISupportQtvtkRenderingLabelFLANN::FLANN
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hongseok/catkin_ws/src/tutorial
here and i don't know what do you say about the value of PCL_LIBRARIES how can i get that value?

**Comment by kunaltyagi** [comment]
> PCL_LIBRARIES how can i get that value?

It's already there in the output

**Comment by suk8267** [comment]
ah. i am not good at linux, i'm sorry

**Comment by suk8267** [comment]
@kunaltyagi so, i foud that line 'looking for PCL_VISUALIZATION' but i can't found 'found  PCL_VISUALIZATION'. is this the reason of error?

**Comment by kunaltyagi** [comment]
I can't understand why you're receiving the issue apart from the missing Python VTK library. The `pcl_visualization` library is present in the line below all the `looking for PCL_....`. Could you create a docker image where this is reproduced? That'll help a lot

**Comment by suk8267** [comment]
i don't know how to use docker image, did you mean my project file?

**Comment by suk8267** [comment]
and i install python VTK and it get another cmake error.
-- Eigen found (include: /usr/include/eigen3, version: 3.2.92)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   iostreams
--   serialization
--   regex
CMake Warning at /usr/local/share/pcl-1.9/PCLConfig.cmake:275 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.9/PCLConfig.cmake:334 (find_VTK)
  /usr/local/share/pcl-1.9/PCLConfig.cmake:546 (find_external_library)
  CMakeLists.txt:8 (find_package)


** WARNING ** 2d features related to vtk will be disabled
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
CMake Warning at /usr/local/share/pcl-1.9/PCLConfig.cmake:275 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.9/PCLConfig.cmake:334 (find_VTK)
  /usr/local/share/pcl-1.9/PCLConfig.cmake:546 (find_external_library)
  CMakeLists.txt:8 (find_package)


** WARNING ** io features related to vtk will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
CMake Warning at /usr/local/share/pcl-1.9/PCLConfig.cmake:275 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.9/PCLConfig.cmake:334 (find_VTK)
  /usr/local/share/pcl-1.9/PCLConfig.cmake:549 (find_external_library)
  CMakeLists.txt:8 (find_package)


CMake Error at /usr/local/share/pcl-1.9/PCLConfig.cmake:60 (message):
  visualization is required but vtk was not found
Call Stack (most recent call first):
  /usr/local/share/pcl-1.9/PCLConfig.cmake:365 (pcl_report_not_found)
  /usr/local/share/pcl-1.9/PCLConfig.cmake:549 (find_external_library)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/hongseok/catkin_ws/src/tutorial/build/CMakeFiles/CMakeOutput.log".

**Comment by kunaltyagi** [comment]
There's something wrong with VTK installation of your system. Please check [here](https://github.com/PointCloudLibrary/pcl/blob/master/.dev/docker/env/Dockerfile#L35) for how we install vtk

**Comment by suk8267** [comment]
how can i use dockerfile? i have never use that file

**Comment by kunaltyagi** [comment]
First ensure you install the correct vtk package on your system. If the problem goes away, cool

You don't need to use this dockerfile. Just use this as a guide on how to install dependencies (I'm assuming Ubuntu based system)

**Comment by suk8267** [comment]
hmm what about VTK_version?

**Comment by kunaltyagi** [comment]
8.1 should work. I'll close this issue since it's clear PCL is not the cause of the error. Please head over to gitter to discuss a non-bug in PCL

**Comment by suk8267** [comment]
hmm... i found what is my error. checked my computer, i installed several version of pcl. so i tried to uninstall another version of pcl. is that correct to delete just .h files?

**Comment by kunaltyagi** [comment]
Uninstall them the same way you installed them (make uninstall or apt remove, etc.) There are more files than just the libraries and header files in an installation

**Comment by qlibp** [comment]
@kunaltyagi 

`osrf/ros:noetic-desktop-full` image, encounter similar cmake error
```
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.
```

seems that it's the problem of vtk package, mentioned [here](https://bugs.launchpad.net/ubuntu/+source/vtk7/+bug/1878103)

Any way to make it work?
