### ISSUE TITLE
example_difference_of_normals.cpp(182): error C2668: 'pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval' : ambiguous call to overloaded function

### ISSUE THREAD

**Issue by denadr** [PointCloudLibrary/pcl#1640]
I'm trying to compile the current PCL using Visual Studio 2013 x86.
While building the ALL_BUILD project I get the following error (and some more, but this is the first one):

```
    ------ Build started: Project: pcl_example_difference_of_normals, Configuration: Release Win32 ------
        Building Custom Rule .../pcl-master/examples/features/CMakeLists.txt
        CMake does not need to re-run because ...\pcl-master\examples\features\CMakeFiles\generate.stamp is up-to-date.
        example_difference_of_normals.cpp
   ...\pcl-master\examples\features\example_difference_of_normals.cpp(182): error C2668: 'pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval' : ambiguous call to overloaded function
             ...\pcl-master\filters\include\pcl/filters/conditional_removal.h(702): could be 'pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval(const pcl::ConditionalRemoval<PointOutT> &)'
             ...\pcl-master\filters\include\pcl/filters/conditional_removal.h(632): or       'pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval(boost::shared_ptr<pcl::ConditionBase<PointT>>,bool)'
             with
             [
                     PointT=PointOutT
             ]
             ...\pcl-master\filters\include\pcl/filters/conditional_removal.h(618): or       'pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval(int)'
             while trying to match the argument list '(boost::shared_ptr<pcl::ConditionOr<PointOutT>>)'
```

The same errors occur in the debug configuration of the solution/project, too.
Any hints to solve this problem?
The CMake configuration and generation are working fine. I generated PCL with the visualization module and provided all dependencies (Boost, Eigen, flann, VTK, gTest).
I'm working on a Windows 8.1 x64 machine.

**Comment by UnaNancyOwen** [comment]
Please re-try after add the following code to your source code.

```cpp
#define PCL_NO_PRECOMPILE
```

Or, add the following description to your CMakeLists.txt.

```cmake
add_definitions( -DPCL_NO_PRECOMPILE )
```

**Comment by SergioRAgostinho** [comment]
Is this the current master you're trying to compile? Because I'm finding strange that [these lines](https://github.com/PointCloudLibrary/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L182-L183) would generate the error you just pasted, which report an ambiguous call to ```pcl::ConditionalRemoval<PointOutT>::ConditionalRemoval```. Looking at the [inheritance diagram](http://docs.pointclouds.org/trunk/classpcl_1_1_condition_or.html#dynsection-0), they don't seem related.

**Comment by VictorLamoine** [comment]
Also see #1097

**Comment by SergioRAgostinho** [comment]
@denadr Do you have OMP enabled as well? If so, does it appear disabling it?

**Comment by denadr** [comment]
@SergioRAgostinho I'm sorry, but never heard about that. What does OMP mean? OpenMP? And how can I disable it?

**Comment by SergioRAgostinho** [comment]
@denadr Yes OpenMP. AFAIK you need to pass a specific flag in CMake to enable it. So I'm assuming it's disabled in your case.

**Comment by UnaNancyOwen** [comment]
@denadr I couldn't to reproduce this issue on my environment. Can you share the CMakeCache.txt?

**Comment by Chungzuwalla** [comment]
To check if OpenMP is enabled in your VS 2013 project:
Open Project Properties (in Solution Explorer, right-click project and click Properties)
Go to Configuration Properties -> C/C++ -> Language.
If Open MP Support is set to "Yes (/openmp)" it is on.
If it is blank, or "No (/openmp-)", it is off.
