### ISSUE TITLE
Trouble with pcl_visualization when compiling on OS X

### ISSUE THREAD

**Issue by dkelo** [PointCloudLibrary/pcl#1192]
Hi!
This is my first time working with github, PCL and advanced command-lines, so if I seem like a noob, it's because i am!

I am trying to compile PCL (with visualization) on OSX 10.10.2 following [this guide](http://pointclouds.org/documentation/tutorials/compiling_pcl_macosx.php#compiling-pcl-macosx), but have run into a problem i can't fix by googling. Everything runs without issues, until i execute the make command.
After much work, I got the compiler running up to 48%, before I hit this error:

> Linking CXX shared library ../lib/libpcl_visualization.dylib
> Undefined symbols for architecture x86_64:

After working on fixing this for the last couple of hours, I need your help! 
My suspicion is, that it's a VTK issue, but I'm not sure how to fix it. I have installed VTK in all possible ways, both from binaries and by compiling from source. 

It has to be said, that I am pretty green in this sort of thing, so I might be missing something completely obvious!
Is this the right place to post these questions? If not, please say so and direct me to the right forum! :)

Here is the error-print from Terminal: 
I have included all the lines related to pcl_visualization

```
Scanning dependencies of target pcl_visualization
[ 43%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/point_picking_event.cpp.o
[ 43%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/interactor_style.cpp.o
[ 43%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/point_cloud_handlers.cpp.o
[ 44%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/pcl_visualizer.cpp.o
[ 44%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/histogram_visualizer.cpp.o
[ 44%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/common/common.cpp.o
[ 44%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/common/io.cpp.o
[ 45%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/common/shapes.cpp.o
[ 45%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/common/ren_win_interact_map.cpp.o
[ 45%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/cloud_viewer.cpp.o
[ 45%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/image_viewer.cpp.o
[ 46%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/window.cpp.o
[ 46%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/range_image_visualizer.cpp.o
[ 46%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/common/float_image_utils.cpp.o
[ 46%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/vtk/pcl_image_canvas_source_2d.cpp.o
[ 47%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/vtk/pcl_context_item.cpp.o
[ 47%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/vtk/vtkVertexBufferObject.cxx.o
[ 47%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/vtk/vtkVertexBufferObjectMapper.cxx.o
[ 47%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/vtk/vtkRenderWindowInteractorFix.cpp.o
[ 48%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/pcl_painter2D.cpp.o
[ 48%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/pcl_plotter.cpp.o
[ 48%] Building CXX object visualization/CMakeFiles/pcl_visualization.dir/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm.o
Linking CXX shared library ../lib/libpcl_visualization.dylib
Undefined symbols for architecture x86_64:
  "vtkObjectBase::PrintHeader(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PointPickingCallback in point_picking_event.cpp.o
      vtable for pcl::visualization::PCLVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitMainLoopTimerCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::FPSCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizer::ExitMainLoopTimerCallback in histogram_visualizer.cpp.o
      ...
  "vtkObjectBase::PrintTrailer(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PointPickingCallback in point_picking_event.cpp.o
      vtable for pcl::visualization::PCLVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitMainLoopTimerCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::FPSCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizer::ExitMainLoopTimerCallback in histogram_visualizer.cpp.o
      ...
  "vtkObjectBase::CollectRevisions(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      vtable for pcl::visualization::PointPickingCallback in point_picking_event.cpp.o
      vtable for pcl::visualization::PCLVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizerInteractorStyle in interactor_style.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitMainLoopTimerCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::FPSCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizer::ExitMainLoopTimerCallback in histogram_visualizer.cpp.o
      ...
  "vtkObjectBase::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PointPickingCallback in point_picking_event.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitMainLoopTimerCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::ExitCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLVisualizer::FPSCallback in pcl_visualizer.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizer::ExitMainLoopTimerCallback in histogram_visualizer.cpp.o
      vtable for pcl::visualization::PCLHistogramVisualizer::ExitCallback in histogram_visualizer.cpp.o
      vtable for pcl::visualization::ImageViewer::ExitCallback in image_viewer.cpp.o
      ...
  "vtkContextItem::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PCLContextImageItem in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::Point in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::Line in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::Circle in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::Disk in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::Rectangle in pcl_context_item.cpp.o
      vtable for pcl::visualization::context_items::FilledRectangle in pcl_context_item.cpp.o
      ...
  "vtkImageCanvasSource2D::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PCLImageCanvasSource2D in pcl_image_canvas_source_2d.cpp.o
  "vtkInteractorStyleImage::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::ImageViewerInteractorStyle in image_viewer.cpp.o
  "vtkCocoaRenderWindowInteractor::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for vtkCocoaRenderWindowInteractorFix in vtkRenderWindowInteractorFix.mm.o
  "vtkInteractorStyleRubberBandPick::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PCLVisualizerInteractorStyle in interactor_style.cpp.o
  "vtkInteractorStyleTrackballCamera::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for pcl::visualization::PCLHistogramVisualizerInteractorStyle in interactor_style.cpp.o
  "vtkMapper::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for vtkVertexBufferObjectMapper in vtkVertexBufferObjectMapper.cxx.o
  "vtkObject::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtkVertexBufferObject::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkVertexBufferObject.cxx.o
  "operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkWeakPointerBase const&)", referenced from:
      vtkVertexBufferObject::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkVertexBufferObject.cxx.o
  "operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent const&)", referenced from:
      vtkVertexBufferObject::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkVertexBufferObject.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libpcl_visualization.1.8.0.dylib] Error 1
make[1]: *** [visualization/CMakeFiles/pcl_visualization.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dkelo** [comment]
As a followup, I just tried compiling OpenCV, which runs until 98%, and then returns errors, again VTK-related. 
I'll try to completely uninstall VTK, and install it from scratch. Any suggestion on which version i should use?
```
[ 98%] Building CXX object modules/viz/CMakeFiles/opencv_viz.dir/src/vtk/vtkCocoaInteractorFix.mm.o
Linking CXX shared library ../../lib/libopencv_viz.dylib
Undefined symbols for architecture x86_64:
  "vtkObjectBase::PrintHeader(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::Viz3d::VizImpl::TimerCallback in vizimpl.cpp.o
      vtable for cv::viz::Viz3d::VizImpl::ExitCallback in vizimpl.cpp.o
      vtable for cv::viz::vtkCloudMatSink in vtkCloudMatSink.cpp.o
      vtable for cv::viz::vtkCloudMatSource in vtkCloudMatSource.cpp.o
      vtable for cv::viz::vtkImageMatSource in vtkImageMatSource.cpp.o
      vtable for cv::viz::vtkOBJWriter in vtkOBJWriter.cpp.o
      vtable for cv::viz::vtkTrajectorySource in vtkTrajectorySource.cpp.o
      ...
  "vtkObjectBase::PrintTrailer(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::Viz3d::VizImpl::TimerCallback in vizimpl.cpp.o
      vtable for cv::viz::Viz3d::VizImpl::ExitCallback in vizimpl.cpp.o
      vtable for cv::viz::vtkCloudMatSink in vtkCloudMatSink.cpp.o
      vtable for cv::viz::vtkCloudMatSource in vtkCloudMatSource.cpp.o
      vtable for cv::viz::vtkImageMatSource in vtkImageMatSource.cpp.o
      vtable for cv::viz::vtkOBJWriter in vtkOBJWriter.cpp.o
      vtable for cv::viz::vtkTrajectorySource in vtkTrajectorySource.cpp.o
      ...
  "vtkObjectBase::CollectRevisions(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      vtable for cv::viz::Viz3d::VizImpl::TimerCallback in vizimpl.cpp.o
      vtable for cv::viz::Viz3d::VizImpl::ExitCallback in vizimpl.cpp.o
      vtable for cv::viz::vtkCloudMatSink in vtkCloudMatSink.cpp.o
      vtable for cv::viz::vtkCloudMatSource in vtkCloudMatSource.cpp.o
      vtable for cv::viz::vtkImageMatSource in vtkImageMatSource.cpp.o
      vtable for cv::viz::vtkOBJWriter in vtkOBJWriter.cpp.o
      vtable for cv::viz::vtkTrajectorySource in vtkTrajectorySource.cpp.o
      ...
  "vtkObjectBase::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::Viz3d::VizImpl::TimerCallback in vizimpl.cpp.o
      vtable for cv::viz::Viz3d::VizImpl::ExitCallback in vizimpl.cpp.o
  "vtkImageAlgorithm::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::vtkImageMatSource in vtkImageMatSource.cpp.o
  "vtkInteractorStyle::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      cv::viz::vtkVizInteractorStyle::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkVizInteractorStyle.cpp.o
  "vtkPolyDataAlgorithm::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::vtkCloudMatSource in vtkCloudMatSource.cpp.o
      vtable for cv::viz::vtkTrajectorySource in vtkTrajectorySource.cpp.o
      cv::viz::vtkXYZReader::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkXYZReader.cpp.o
  "vtkCocoaRenderWindowInteractor::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for cv::viz::vtkCocoaRenderWindowInteractorFix in vtkCocoaInteractorFix.mm.o
  "vtkWriter::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      cv::viz::vtkCloudMatSink::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkCloudMatSink.cpp.o
      cv::viz::vtkOBJWriter::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkOBJWriter.cpp.o
      cv::viz::vtkXYZWriter::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkXYZWriter.cpp.o
  "operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent const&)", referenced from:
      cv::viz::vtkCloudMatSink::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkCloudMatSink.cpp.o
      cv::viz::vtkOBJWriter::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkOBJWriter.cpp.o
      cv::viz::vtkVizInteractorStyle::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkVizInteractorStyle.cpp.o
      cv::viz::vtkXYZReader::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkXYZReader.cpp.o
      cv::viz::vtkXYZWriter::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkXYZWriter.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_viz.3.0.0.dylib] Error 1
make[1]: *** [modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by VictorLamoine** [comment]
Hello,

The right place to ask questions is the [pcl-users mailing list](http://www.pcl-users.org/), don't forget to register!
This is an issue/bug tracker, please report here problems in PCL algorithms, bugs... or compilation problems that are not due to a misconfiguration on your side. In your case the tutorial might need an update so I think it's ok to keep this issue open.

PCL works great with VTK 5.8, support for newer version like VTK 6.1 or 6.2 should be really good too.
If it doesn't work with VTK 5.8 binaries, I suggest compiling VTK 6.2 with the following CMake flags: (+ the one mentioned in the tutorial)

```cmake
 BUILD_DOCUMENTATION              OFF                                                                                                                                                                     
 BUILD_EXAMPLES                   OFF                                                                                                                                                                     
 BUILD_SHARED_LIBS                ON                                                                                                                                                                      
 BUILD_TESTING                    ON                                                                                                                                                                      
 BUILD_USER_DEFINED_LIBS          OFF                                                                                                                                                                     
 CMAKE_BUILD_TYPE                 Debug                                                                                                                                                                   
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                                                                                              
 CTEST_TEST_TIMEOUT               3600                                                                                                                                                                    
 VTK_ANDROID_BUILD                OFF                                                                                                                                                                     
 VTK_EXTRA_COMPILER_WARNINGS      OFF                                                                                                                                                                     
 VTK_Group_Imaging                ON                                                                                                                                                                      
 VTK_Group_MPI                    ON                                                                                                                                                                      
 VTK_Group_Qt                     ON                                                                                                                                                                      
 VTK_Group_Rendering              ON                                                                                                                                                                      
 VTK_Group_StandAlone             ON                                                                                                                                                                      
 VTK_Group_Tk                     ON                                                                                                                                                                      
 VTK_Group_Views                  ON                                                                                                                                                                      
 VTK_Group_Web                    OFF                                                                                                                                                                     
 VTK_IOS_BUILD                    OFF                                                                                                                                                                     
 VTK_PYTHON_VERSION               2                                                                                                                                                                       
 VTK_RENDERING_BACKEND            OpenGL                                                                                                                                                                  
 VTK_SMP_IMPLEMENTATION_TYPE      Sequential                                                                                                                                                              
 VTK_USE_LARGE_DATA               OFF                                                                                                                                                                     
 VTK_WRAP_JAVA                    OFF                                                                                                                                                                     
 VTK_WRAP_PYTHON                  OFF                                                                                                                                                                     
 VTK_WRAP_TCL                     OFF      
```

Bye

**Comment by fran6co** [comment]
Why don't you try with these instructions => http://pointclouds.org/documentation/tutorials/installing_homebrew.php#installing-homebrew

**Comment by l0g1x** [comment]
I have the exact same issue as @dkelo . I could not find his follow up post on pcl users mailing list. @fran6co I did install pcl via homebrew, but for some reason when i try to compile the qt-visualizations tutorial example with cmake, i receive a error stating that <pcl/visualization/pcl_visualizer.h> was not found, but all the other pcl includes where found. 

@VictorLamoine Why do you think disabling VTK_Group_Web during compile would fix the issue? Ive also been trying to get qt5 and VTK 6.2 working, but with absolutely no success at whatever approach i took. Specifically, im trying to just get the qt-visualizations tutorial to work.

**Comment by VictorLamoine** [comment]
My configuration was just an example, It's just that I did not enable `VTK_Group_Web`.

I did not test with VTK 6.x versions my Qt tutorial, I will try in the following days (Linux) but I doubt it will work.

Many things have changed for VTK 6.x regarding `CMake`, the tutorial would need a serious update but I don't have time for this now and I still do not understand everything in the new VTK macros.

**Comment by ajabri** [comment]
@l0g1x Did you end up figuring out this issue?

**Comment by niebayes** [comment]
1. pull the latest repo of g2o from Github.
2. compile it.
3. find_package() 
4. include_directories()
5. target_link_libraries() --- NOTICE: G2O has two libraries ${G2O_CORE_LIBRARY} and ${G2O_STUFF_LIBRARY}, instead of the ordinary one ${G2O_LIBRARIES}. You need to specify both of them in this command.

**Comment by SergioRAgostinho** [comment]
Closing this since whatever happened here is not longer applicable to the current version of PCL. We're building visualization in CI for High Sierra and Catalina. 
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=16272&view=logs&j=eb6fcca7-7d1a-5fb6-a052-b530c1724910
