### ISSUE TITLE
[compile error] "Octree2BufBase failed in pcl 1.12.1"

### ISSUE THREAD

**Issue by danielTobon43** [PointCloudLibrary/pcl#5246]
**Describe the error**
I would like to compile a dbscan project that uses octrees from pcl. The project fails when importing:

`#include <pcl/octree/octree_impl.h>`

```
[ 16%] Building CXX object CMakeFiles/dbscan.dir/main.cpp.o
In file included from /usr/include/pcl-1.12/pcl/io/low_level_io.h:65,
                 from /usr/include/pcl-1.12/pcl/io/impl/pcd_io.hpp:50,
                 from /usr/include/pcl-1.12/pcl/io/pcd_io.h:789,
                 from /usr/src/include/dbScan.h:17,
                 from /usr/src/main.cpp:48:
/usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
      |  ^~~~~~~
In file included from /usr/include/pcl-1.12/pcl/octree/octree_impl.h:41,
                 from /usr/src/include/OctreeGenerator.h:14,
                 from /usr/src/main.cpp:47:
/usr/include/pcl-1.12/pcl/octree/impl/octree2buf_base.hpp:46:1: error: 'Octree2BufBase' does not name a type
   46 | Octree2BufBase<LeafContainerT, BranchContainerT>::Octree2BufBase()
      | ^~~~~~~~~~~~~~
/usr/include/pcl-1.12/pcl/octree/impl/octree2buf_base.hpp:59:1: error: 'Octree2BufBase' does not name a type
   59 | Octree2BufBase<LeafContainerT, BranchContainerT>::~Octree2BufBase()
      | ^~~~~~~~~~~~~~
/usr/include/pcl-1.12/pcl/octree/impl/octree2buf_base.hpp:69:15: error: expected initializer before '<' token
   69 | Octree2BufBase<LeafContainerT, BranchContainerT>::setMaxVoxelIndex(
      |               ^
/usr/include/pcl-1.12/pcl/octree/impl/octree2buf_base.hpp:106:15: error: expected initializer before '<' token
  106 | Octree2BufBase<LeafContainerT, BranchContainerT>::findLeaf(uindex_t idx_x_arg,
.
.
.
/usr/include/pcl-1.12/pcl/octree/impl/octree_iterator.hpp:345:35: error: expected initializer before '<' token
  345 | OctreeLeafNodeBreadthFirstIterator<OctreeT>::reset()
      |                                   ^
/usr/include/pcl-1.12/pcl/octree/impl/octree_iterator.hpp:353:1: error: 'OctreeLeafNodeBreadthFirstIterator' does not name a type
  353 | OctreeLeafNodeBreadthFirstIterator<OctreeT>&
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/pcl-1.12/pcl/octree/impl/octree_iterator.hpp:366:1: error: 'OctreeLeafNodeBreadthFirstIterator' does not name a type
  366 | OctreeLeafNodeBreadthFirstIterator<OctreeT>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/pcl-1.12/pcl/octree/octree_impl.h:44,
                 from /usr/src/include/OctreeGenerator.h:14,
                 from /usr/src/main.cpp:47:
/usr/include/pcl-1.12/pcl/octree/impl/octree_pointcloud.hpp:53:14: error: 'OctreePointCloud' in namespace 'pcl::octree' does not name a template type

   53 | pcl::octree::OctreePointCloud<PointT, LeafContainerT, BranchContainerT, OctreeT>::

```

**To Reproduce**

I am trying to compile a dbscan-octrees [project](https://github.com/danielTobon43/DBScan-PCL-Optimized.git) with cmake and pcl 1.12.1. It works with pcl 1.9.1/1.8.0 but, fails with pcl 1.12.1.

**Your Environment (please complete the following information):**

 - OS: [e.g. linux alpine 3.15]
 - Compiler: gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, g++ (Alpine 10.3.1_git20211027) 10.3.1 20211027
 - PCL Version: 1.12.1
 - PCL Type: compiled from source with cmake 3.21.3 (the compilation ends successfully)

**Possible solution**

- I have set c++ standard 14 --> not working

**Comment by danielTobon43** [comment]
I have found the solution:

I think the import statement changed:

I have replace from:

`#include <pcl/octree/octree_impl.h>`

to: 

`#include <pcl/octree/octree.h>`

and the project is working now.
